### ISSUE TITLE
Indent option doesn't seem to be working for arrays of objects

### ISSUE THREAD

**Issue by dockleryxk** [KenanY/json2toml#159]
For some reason, I can't get the indent option to work. 

I made a small reproduction here: https://replit.com/@RichardJeffords/json2toml-indent-issue

I am using node v16.14.0

Here is a node (no typescript) version of the code, still with the same issue:

```node
var json2toml = require("json2toml")
var fs = require("fs")

// list of domains to redirect
var domains = [
  "olddomain1.com",
  "olddomain2.com",
  "olddomain3.com",
]

var newDomain = "https://www.newdomain.com"

function run() {
  var domainsWithPrefixes = []
  domains.forEach(domain => {
    domainsWithPrefixes.push(`http://${ domain }`)
    domainsWithPrefixes.push(`http://${ domain }/*`)
    domainsWithPrefixes.push(`http://www.${ domain }`)
    domainsWithPrefixes.push(`http://www.${ domain }/*`)
    domainsWithPrefixes.push(`https://${ domain }`)
    domainsWithPrefixes.push(`https://${ domain }/*`)
    domainsWithPrefixes.push(`https://www.${ domain }`)
    domainsWithPrefixes.push(`https://www.${ domain }/*`)
  })
  var redirects = domainsWithPrefixes.map(u => ({ from: u, to: newDomain, status: 301, force: true }))
  var toml = json2toml({ redirects }, { indent: 2, newlineAfterSection: true })

  var fname, baseFname
  if (newDomain.includes("www")) {
    baseFname = newDomain.split(".")[1]
    fname = `${ baseFname }.toml`
  }
  else {
    baseFname = newDomain.split(".")[0].replace("https://", "")
    fname = `${ baseFname }.toml`
  }

  var i = 1
  while (fs.existsSync(fname)) {
    fname = `${ baseFname }_${ i++ }.toml`
  }

  fs.writeFileSync(fname, toml)
}

run()
```

## output:

```toml
[[redirects]]
force = true
from = "http://olddomain1.com"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "http://olddomain1.com/*"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "http://www.olddomain1.com"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "http://www.olddomain1.com/*"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "https://olddomain1.com"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "https://olddomain1.com/*"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "https://www.olddomain1.com"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "https://www.olddomain1.com/*"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "http://olddomain2.com"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "http://olddomain2.com/*"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "http://www.olddomain2.com"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "http://www.olddomain2.com/*"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "https://olddomain2.com"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "https://olddomain2.com/*"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "https://www.olddomain2.com"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "https://www.olddomain2.com/*"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "http://olddomain3.com"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "http://olddomain3.com/*"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "http://www.olddomain3.com"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "http://www.olddomain3.com/*"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "https://olddomain3.com"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "https://olddomain3.com/*"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "https://www.olddomain3.com"
status = 301
to = "https://www.newdomain.com"

[[redirects]]
force = true
from = "https://www.olddomain3.com/*"
status = 301
to = "https://www.newdomain.com"
```

## expected output:

```toml
[[redirects]]
  force = true
  from = "http://olddomain1.com"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "http://olddomain1.com/*"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "http://www.olddomain1.com"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "http://www.olddomain1.com/*"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "https://olddomain1.com"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "https://olddomain1.com/*"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "https://www.olddomain1.com"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "https://www.olddomain1.com/*"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "http://olddomain2.com"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "http://olddomain2.com/*"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "http://www.olddomain2.com"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "http://www.olddomain2.com/*"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "https://olddomain2.com"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "https://olddomain2.com/*"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "https://www.olddomain2.com"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "https://www.olddomain2.com/*"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "http://olddomain3.com"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "http://olddomain3.com/*"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "http://www.olddomain3.com"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "http://www.olddomain3.com/*"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "https://olddomain3.com"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "https://olddomain3.com/*"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "https://www.olddomain3.com"
  status = 301
  to = "https://www.newdomain.com"

[[redirects]]
  force = true
  from = "https://www.olddomain3.com/*"
  status = 301
  to = "https://www.newdomain.com"
```

Please let me know if I can provide more details about my issue or how to reproduce it. Thank you!
